---
- name: configure httpd using template
  template:
    src: templates/http.j2
    dest: /var/www/html/index.html
  notify: restart httpd

- name: Configure httpd using file content as a block
  lineinfile:
    path: /var/www/html/index.html
    line: "{{ lookup('file', 'files/http_webfile') }}"
  notify: restart httpd



